version: "3.9"
services:
  restaurant_service_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_service_server
    restart: on-failure
    ports:
      - 8092:8092
    environment:
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL:-jdbc:mysql://mysql:3306/restaurant_service}"
      SPRING_DATASOURCE_USERNAME: "${SPRING_DATASOURCE_USERNAME:-root}"
      SPRING_DATASOURCE_PASSWORD: "${SPRING_DATASOURCE_PASSWORD:-root}"
      SPRING_RABBITMQ_HOST: "${RABBITMQ_HOST:-rabbitmq}"
      SPRING_RABBITMQ_PORT: "${RABBITMQ_PORT:-5672}"
      SPRING_RABBITMQ_USERNAME: "${RABBITMQ_USERNAME:-user}"
      SPRING_RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD:-password}"
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - ku-wongnai_ku-wongnai

networks:
  ku-wongnai_ku-wongnai:
    external: true
