version: "3.9"
services:
  mysql:
    image: mysql
    # container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: restaurant
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - db_data:/var/lib/mysql
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5673:5672" # RabbitMQ default port for AMQP
      - "15672:15672" # RabbitMQ Management Console
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - user-service_sail

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 8081:80
    depends_on:
      - mysql

volumes:
  db_data:

networks:
  user-service_sail:
    external: true
